// <auto-generated />
using System;
using GroceryStoreAPI.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GroceryStoreAPI.Migrations
{
    [DbContext(typeof(CustomerContext))]
    [Migration("20210415185158_AddedNewAttributesToCustomer")]
    partial class AddedNewAttributesToCustomer
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.14");

            modelBuilder.Entity("GroceryStoreAPI.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(20);

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("82c98f0c-2093-4ef7-8bd4-a13e00c4d02e"),
                            Address = "449 Simcoe St., London ON N6L 1Z7",
                            Age = 28,
                            CreatedDate = new DateTimeOffset(new DateTime(2021, 4, 15, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -4, 0, 0, 0)),
                            Email = "darryl.gollan@gmail.com",
                            Name = "Darryl",
                            Phone = "226-268-4611"
                        },
                        new
                        {
                            Id = new Guid("ef0c4d03-12b4-4677-8eed-801ce18fc883"),
                            Address = "433 Dufferin Ave., London ON N6L 1Z7",
                            Age = 38,
                            CreatedDate = new DateTimeOffset(new DateTime(2021, 4, 15, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -4, 0, 0, 0)),
                            Email = "michelle@gmail.com",
                            Name = "Michelle",
                            Phone = "226-268-6611"
                        },
                        new
                        {
                            Id = new Guid("38d93d92-b202-41c1-a441-66e283d50f25"),
                            Address = "523 Brringer St., Belleville ON N6L 1Z7",
                            Age = 64,
                            CreatedDate = new DateTimeOffset(new DateTime(2021, 4, 15, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -4, 0, 0, 0)),
                            Email = "sandy@gmail.com",
                            Name = "Sandy",
                            Phone = "613-233-9811"
                        },
                        new
                        {
                            Id = new Guid("641f530d-dd74-4d57-91a8-66ff7443669b"),
                            Address = "444 Oxford St West, London ON N6L 1Z7",
                            Age = 44,
                            CreatedDate = new DateTimeOffset(new DateTime(2021, 4, 15, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -4, 0, 0, 0)),
                            Email = "sandra@gmail.com",
                            Name = "Sandra",
                            Phone = "519-232-9877"
                        },
                        new
                        {
                            Id = new Guid("286abd03-f3d8-49d4-aef3-35cf3a9d66d4"),
                            Address = "923 Oxford St West, London ON N6L 1Z7",
                            Age = 54,
                            CreatedDate = new DateTimeOffset(new DateTime(2021, 4, 15, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -4, 0, 0, 0)),
                            Email = "raichel@gmail.com",
                            Name = "Raichel",
                            Phone = "519-232-8823"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
